- action: write_file
  dest: server.cfg
  data: |
    sv_hostname "FiveCore RP Server"
    sv_maxclients 8
    endpoint_add_tcp "0.0.0.0:30120"
    endpoint_add_udp "0.0.0.0:30120"

    ensure fivecore
    ensure five-policejob
    ensure five-truckerjob
    ensure five-garbagejob
    ensure five-taxijob
    ensure five-ambulancejob

    set mongodb_uri "mongodb://localhost:27017"
    set mongodb_database "fivecore"
